version: '3'

services:
  user_managment_api:
    build:
      context: .
      dockerfile: DockerFile
      args:
        DEPLOY: ${DEPLOY}
    ports:
      - 3000:3000
    volumes:
      - .:/user_managment_api
    networks:
      - my_network
    depends_on:
      - database
    container_name: user_managment_api
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'
    env_file:
      - .env

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    container_name: mysql-database
    networks:
      - my_network
    ports:
      - 3309:3306
    volumes:
      - mysql-data:/var/lib/mysql 

volumes:
  mysql-data:

networks:
  my_network:
    driver: bridge